apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yugabyte
  namespace: yugabyte
spec:
  serviceName: "yugabyte"
  replicas: 1
  selector:
    matchLabels:
      app: yugabyte
  template:
    metadata:
      labels:
        app: yugabyte
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: yugabyte
          image: yugabytedb/yugabyte:latest
          ports:
            - containerPort: 5433
              name: ycql
            - containerPort: 9042
              name: ysql
          volumeMounts:
            - mountPath: /var/lib/yugabyte
              name: yugabyte-storage
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          securityContext:
            runAsUser: 2000
            allowPrivilegeEscalation: false
  volumeClaimTemplates:
    - metadata:
        name: yugabyte-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            memory: "1Gi"  # Increase from 512Mi
            cpu: "500m"    # Increase from 250m
          limits:
            memory: "2Gi"  # Increase from 1Gi
            cpu: "1"       # Increase from 500m
            