apiVersion: v1
kind: Service
metadata:
  name: yugabyte
  namespace: yugabyte
spec:
  clusterIP: None
  selector:
    app: yugabyte
  ports:
    - name: ycql
      port: 5433
      targetPort: 5433
    - name: ysql
      port: 9042
      targetPort: 9042
