apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--log-level=debug"
          ports:
            - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: default
spec:
  ports:
    - name: http
      port: 8181
      targetPort: 8181
  selector:
    app: opa
