apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  namespace: microservices-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: service-2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4400
          env:
            - name: PORT
              value: "4400"
