apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: your-dockerhub-username/service-2:latest
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              value: "4001"
