apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  namespace: microservices-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
        - name: service-1
          image: dahunsij/service-1:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"

